version: "3.8"

services:
  db:
    image: postgres:16
    container_name: local-pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: container_instances_metrics
    volumes:
      - local-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local-pgdata:
  pgadmin-data:
